#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(SNATCH) \
    F(OVERHEAT)\
    F(ROOST)\
    F(FOCUS_BLAST)\
    F(ENERGY_BALL)\
    F(FALSE_SWIPE)\
    F(BRINE)\
    F(FLING)\
    F(CHARGE_BEAM)\
    F(ENDURE)\
    F(DRAGON_PULSE)\
    F(DRAIN_PUNCH)\
    F(WILL_O_WISP)\
    F(SILVER_WIND)\
    F(EMBARGO)\
    F(EXPLOSION)\
    F(SHADOW_CLAW)\
    F(PAYBACK)\
    F(RECYCLE)\
    F(GIGA_IMPACT)\
    F(ROCK_POLISH)\
    F(DAZZLING_GLEAM)\
    F(STONE_EDGE)\
    F(AVALANCHE)\
    F(THUNDER_WAVE)\
    F(GYRO_BALL)\
    F(SWORDS_DANCE)\
    F(STEALTH_ROCK)\
    F(PSYCH_UP)\
    F(CAPTIVATE)\
    F(DARK_PULSE)\
    F(ROCK_SLIDE)\
    F(X_SCISSOR)\
    F(SLEEP_TALK)\
    F(NATURAL_GIFT)\
    F(POISON_JAB)\
    F(DREAM_EATER)\
    F(GRASS_KNOT)\
    F(SWAGGER)\
    F(PLUCK)\
    F(U_TURN)\
    F(SUBSTITUTE)\
    F(FLASH_CANNON)\
    F(TRICK_ROOM)\
    F(SCALD)\
    F(PLAY_ROUGH)\
    F(BUG_BUZZ)\
    F(VOLT_SWITCH)\
    F(BABY_DOLL_EYES)\
    F(TRI_ATTACK)\
    F(FAIRY_WIND)\
    F(SHEER_COLD)\
    F(TELEPORT)\
    F(DYNAMIC_PUNCH)\
    F(ZAP_CANNON)\
    F(CURSE)\
    F(PAY_DAY)\
    F(HEADBUTT)\
    F(THUNDER_FANG)\
    F(ICE_FANG)\
    F(FIRE_FANG)\
    F(DOUBLE_EDGE)\
    F(FURY_CUTTER)\
    F(METRONOME)\
    F(MIMIC)\
    F(ROLLOUT)\
    F(WEATHER_BALL)\
    F(POWER_UP_PUNCH)\
    F(WILD_CHARGE)\
    F(HELPING_HAND)\
    F(SOFT_BOILED)\
    F(DRAGON_RAGE)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
