MoveTutor_Text_SwaggerTeach:
	.string "Heh! My POKéMON totally rules!\n"
	.string "It's cooler than any POKéMON!\p"
	.string "I was lipping off with a swagger in\n"
	.string "my step like that when the CHAIRMAN\l"
	.string "chewed me out.\p"
	.string "That took the swagger out of my step.\p"
	.string "Here's the TM for SWAGGER.$"

MoveTutor_Text_SwaggerTaught:
	.string "I'll just praise my POKéMON from now\n"
	.string "on without the swagger.$"

MoveTutor_Text_RolloutTeach:
	.string "Did you know that you can go from\n"
	.string "here a long way in that direction\l"
	.string "without changing direction?\p"
	.string "I might even be able to roll\n"
	.string "that way.\p"
	.string "Do you think your POKéMON will\n"
	.string "want to roll, too?\p"
	.string "Here's the TM for ROLLOUT.$"

MoveTutor_Text_RolloutTaught:
	.string "Rolling around in the grass makes me\n"
	.string "happy. Come on, let's roll!$"

MoveTutor_Text_FuryCutterTeach:
	.string "There's a move that gets stronger\n"
	.string "when you keep using it in a row.\p"
	.string "It's a BUG-type move, and it is\n"
	.string "wickedly cool.\p"
	.string "It's called FURY CUTTER.\n"
	.string "Here's the TM for FURY CUTTER.$"

MoveTutor_Text_FuryCutterTaught:
	.string "I get a thrill watching to see if\n"
	.string "the move keeps hitting in succession!$"

MoveTutor_Text_MimicTeach:
	.string "Ah, young one!\p"
	.string "I am also a young one, but I mimic\n"
	.string "the styles and speech of the elderly\l"
	.string "folks of this town.\p"
	.string "What do you say, young one?\n"
	.string "Here's the TM for MIMIC.$"

MoveTutor_Text_MimicTaught:
	.string "MIMIC is a move of great depth.\p"
	.string "Could you execute it to perfection\n"
	.string "as well as me…?$"

MoveTutor_Text_MetronomeTeach:
	.string "I want all sorts of things!\n"
	.string "But I used up my allowance…\p"
	.string "Wouldn't it be nice if there were\n"
	.string "a spell that made money appear when\l"
	.string "you waggle a finger?\p"
	.string "Here's the TM for METRONOME.$"

MoveTutor_Text_MetronomeTaught:
	.string "When a POKéMON waggles its finger\n"
	.string "like a METRONOME, all sorts of nice\l"
	.string "things happen.\p"
	.string "Wouldn't it be nice if we could\n"
	.string "use it, too?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humph! My wife relies on HIDDEN\n"
	.string "POWER to stay awake.\p"
	.string "She should just take a nap like I do,\n"
	.string "and SLEEP TALK.\p"
	.string "Here's the TM for SLEEP TALK.$"

MoveTutor_Text_SleepTalkTaught:
	.string "I've never once gotten my wife's\n"
	.string "coin trick right.\p"
	.string "I would be happy if I got it right\n"
	.string "even as I SLEEP TALK…$"

MoveTutor_Text_SubstituteTeach:
	.string "When I see the wide world from up\n"
	.string "here on the roof…\p"
	.string "I think about how nice it would be\n"
	.string "if there were more than just one me\l"
	.string "so I could enjoy all sorts of lives.\p"
	.string "Of course it's not possible.\n"
	.string "Giggle…\p"
	.string "Here's the TM for SUBSTITUTE.$"

MoveTutor_Text_SubstituteTaught:
	.string "We human beings should enjoy our\n"
	.string "own lives to the utmost!\p"
	.string "I hope you'll get that way, too!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a FIGHTING-type TRAINER,\n"
	.string "so I can't win at the MOSSDEEP GYM\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Here's the TM for DYNAMIC PUNCH.$"

MoveTutor_Text_DynamicPunchTaught:
	.string "I want you to win at the MOSSDEEP GYM\n"
	.string "using that DYNAMIC PUNCH!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Sigh…\p"
	.string "SOOTOPOLIS's GYM LEADER is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "He's got appeal with a DOUBLE-EDGE.\n"
	.string "I couldn't even catch his eye.\p"
	.string "Here's the TM for DOUBLE-EDGE.$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "I won't live for love anymore!\n"
	.string "I'll become tough!$"

MoveTutor_Text_ExplosionTeach:
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge EXPLOSION of popularity!\p"
	.string "Here's the TM for EXPLOSION.$"

MoveTutor_Text_ExplosionTaught:
	.string "For a long time, I've taught POKéMON\n"
	.string "how to use EXPLOSION, but I've yet\l"
	.string "to ignite my own EXPLOSION…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"
